---
on:
  push:
    tags:
      - '*'

name: Publish release
jobs:
  build:
    name: Build contracts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [mainnet, testnet]
    steps:
      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :
      
      - name: Clone the repository
        uses: actions/checkout@v4
      
      - run: |
          echo $(date) > bin/aurora-${{ matrix.profile }}.wasm
          echo $(date) > bin/aurora-factory-${{ matrix.profile }}.wasm
      
      - run: ls -lH bin/aurora-*${{ matrix.profile }}.wasm
      
      - name: Upload aurora-${{ matrix.profile }}.wasm artifact
        uses: actions/upload-artifact@v4
        with:
          name: contract-${{ matrix.profile }}
          path: bin/aurora*${{ matrix.profile }}.wasm
      
      
      - name: Upload contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: bin/aurora*${{ matrix.profile }}.wasm
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true

  publish:
    name: Publish contracts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: contracts
          pattern: contract-*
          merge-multiple: true

      - run: ls -la contracts
      
      - name: Publish contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: contracts/aurora*.wasm
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          # overwrite: true