name: Run Job Every Minute

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          echo "This job runs every minute."
          exit 1
  
  notifier:
    runs-on: ubuntu-latest
    if: failure()
    needs: run-every-minute
#        uses: actions/slack@v3
    steps:
      - name: Notify
        run: echo "Job failed"
