name: Run Job Every Minute

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          echo "This job runs every minute."
          exit 1

  notifier:
    runs-on: ubuntu-latest
    needs: run-every-minute
    if: failure()
    steps:
      - uses: 8398a7/action-slack@v3
        with:
         status: ${{ job.status }}
         fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
